#server.port=8082
#spring.datasource.url=jdbc:postgresql://localhost:5432/customers
#spring.datasource.username=postgres
#spring.datasource.password=mysecretpassword
#spring.datasource.driverClassName=org.postgresql.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=create-drop

server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customers
    username: postgres
    password: mysecretpassword
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password